version: '2'
services:
  salt:
    build: salt-master
    privileged: true
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./salt-master/salt:/srv/salt
  saltminion:
    build: salt-minion
    privileged: true