version: '2'
services:
  masternode:
    build: salt-master
    privileged: true
    ports:
      - 8000:8000
    volumes:
      - ./salt-master/salt:/srv/salt
      - ./salt-master/pillar:/srv/pillar
  saltminion:
    build: salt-minion
    privileged: true